### ISSUE TITLE
[Off-topic] A question about your bibnotes fork

### ISSUE THREAD

**Issue by Elaws** [DanGonite57/CrPyto#45]
Hello,

I'm sorry to contact you using this way, this is completely off-topic so feel free to ignore if necessary.

I just stumbled upon your bibnotes (Obsidian MD) fork, and was wondering : Once you've forked the repo and then regularly add your own commits, how do you keep your fork updated with the original repo ?

Do you simply `fetch upstream` and `merge` with your fork ?

Thanks a lot

**Comment by DanGonite57** [comment]
Hi, yes, I usually just `pull upstream` and then deal with any merge conflicts.
